AZURE_OPENAI_API_KEY = "4gM2HRtaDIsFbDjfQQl1DAO1RzN4l2TfAcmkIuC0KgcEjmsEOS9yJQQJ99BBACHYHv6XJ3w3AAAAACOGpcKh"
AZURE_OPENAI_ENDPOINT = "https://ppbai6350320563.openai.azure.com"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
AZURE_OPENAI_DEPLOYMENT = "o1"